version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "bump(deps): "

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "bump(docker) "

  - package-ecosystem: github-actions
    directory: /.github/workflows
    schedule:
      interval: monthly
    commit-message:
      prefix: "bump(actions) "
