name: Lint Code Base

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.js*'
      - '**.ts*'
      - Dockerfile
      - package.json
      - pnpm-lock.yaml
      - .github/workflows/ci-lint-codebase.yml

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job not required"
